### ISSUE TITLE
Crash game (1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [MysticMods/Traverse#12]
Hello!
After adding The Twilight Forest mod to the assembly, the game crashes.
[crash-2020-03-02_13.29.10-client.txt](https://github.com/MysticMods/Traverse/files/4274830/crash-2020-03-02_13.29.10-client.txt)
[latest.log](https://github.com/MysticMods/Traverse/files/4274833/latest.log)
Thanks!

**Comment by pimalel233** [comment]
It's not the problem with this mod specifically, if you actually read the crash log:
java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.
You have too many mods that adds, probably biomes, did not read too much into the log. Either uninstall unnecessary mods, disable (unregister) items that are exceeding the range or try JustEnoughIDs but that might conflict with some other mods. It just crashes when Traverse is registering its items as the limit is already reached.

**Comment by SeagalKru** [comment]
Here it is what’s the matter ... I understand you. Thanks!
