### ISSUE TITLE
[1.15] Biomes aren't added to Forge Biome Dictionary

### ISSUE THREAD

**Issue by bonnibel** [MysticMods/Traverse#16]
Biomes aren't properly tagged as overworld biomes in the Biome Dictionary, causing incompatibility with other terrain and biome mods

**Comment by noobanidus** [comment]
To give some context, "properly tagged" is a little bit of a misnomer. I asked a lot of information, whether this was something new, etc, whether you were referring to the BiomeDictionary or the Vanilla tags system.

That said, this "OVERWORLD" tag was implemented about 3 months after the original Traverse for 1.14.4 was released, and I doubt EpicSquid is keeping up-to-date with every Forge update, as he is the one who ported it to 1.15.2. 

I'll endeavor to get this sorted soonish, but I have a lot on my plate at the minute. If someone wishes to do a PR for it, that would be greatly appreciated.
