### ISSUE TITLE
[1.15.2] Traverse logs can't be stripped with an axe

### ISSUE THREAD

**Issue by sargunv** [MysticMods/Traverse#17]
Using version 1.15.2-3.0.0 on Forge
Log: https://paste.ee/p/pcNQS

**Comment by sargunv** [comment]
I see this was fixed in 9debb5f62e7e578884d76fbc08c77bf0fe81e776. Thanks!

**Comment by noobanidus** [comment]
And the release is now available on CurseForge! I've also back-ported the changes to 1.14.4.
