### ISSUE TITLE
Can't light blocks on fire

### ISSUE THREAD

**Issue by Barchtic** [MysticMods/Traverse#21]
**Describe the bug:**
Can't light any Traverse leaves or logs

**To Reproduce:**
1) Right click with flint and steel.

**Expected behavior:**
Similar to regular leaves or logs you can light on the sides of blocks etc.

Forge 31.2.4

**Mystic Mods Versions**

- MysticalLib: 2.0.0
- Traverse: 3.2.0

**Comment by noobanidus** [comment]
Damn, this is still an issue as I forgot to do leaves.
