### ISSUE TITLE
zh_tw file

### ISSUE THREAD

**Issue by ghost** [MysticMods/Traverse#28]
I translated the mod.
edited in 12/31 1:07 GMT+8

{
  "biome.traverse.arid_highlands": "乾旱高原",
  "biome.traverse.autumnal_wooded_hills": "秋日森林丘陵",
  "biome.traverse.autumnal_woods": "秋日森林",
  "biome.traverse.cliffs": "懸崖峭壁",
  "biome.traverse.coniferous_forest": "常綠森林",
  "biome.traverse.coniferous_woodland_hills_biome": "常綠森林丘陵",
  "biome.traverse.desert_shrubland": "沙漠叢帶",
  "biome.traverse.high_coniferous_forest": "高常綠森林",
  "biome.traverse.lush_swamp": "茂密沼澤",
  "biome.traverse.meadow": "肥沃平原",
  "biome.traverse.mini_jungle": "小型叢林",
  "biome.traverse.plains_plateau": "平頂高原",
  "biome.traverse.rocky_edge": "岩地邊緣",
  "biome.traverse.rolling_hills": "連綿丘陵",
  "biome.traverse.snowy_cliffs": "冰雪懸崖峭壁",
  "biome.traverse.snowy_coniferous_forest": "冰雪常綠森林",
  "biome.traverse.snowy_coniferous_wooded_hills": "冰雪常綠森林丘陵",
  "biome.traverse.snowy_high_coniferous_forest": "冰雪高常綠森林",
  "biome.traverse.wooded_island": "密林島嶼",
  "biome.traverse.wooded_plateau": "密林高原",
  "biome.traverse.woodlands": "密林",
  "block.traverse.brown_autumnal_leaves": "棕色秋木樹葉",
  "block.traverse.brown_autumnal_sapling": "棕色秋木樹苗",
  "block.traverse.fir_button": "樅木按鈕",
  "block.traverse.fir_door": "樅木門",
  "block.traverse.fir_fence": "樅木柵欄",
  "block.traverse.fir_fence_gate": "樅木柵欄門",
  "block.traverse.fir_leaves": "樅木樹葉",
  "block.traverse.fir_log": "樅木原木",
  "block.traverse.fir_planks": "樅木木材",
  "block.traverse.fir_pressure_plate": "樅木壓力板",
  "block.traverse.fir_sapling": "樅木樹苗",
  "block.traverse.fir_sign": "樅木告示牌",
  "block.traverse.fir_slab": "樅木半磚",
  "block.traverse.fir_stairs": "樅木階梯",
  "block.traverse.fir_trapdoor": "樅木地板門",
  "block.traverse.fir_wood": "樅木木塊",
  "block.traverse.orange_autumnal_leaves": "橙色秋木樹葉",
  "block.traverse.orange_autumnal_sapling": "橙色秋木樹苗",
  "block.traverse.red_autumnal_leaves": "紅色秋木樹葉",
  "block.traverse.red_autumnal_sapling": "紅色秋木樹苗",
  "block.traverse.stripped_fir_log": "剝皮樅木原木",
  "block.traverse.stripped_fir_wood": "剝皮樅木木塊",
  "block.traverse.yellow_autumnal_leaves": "黃色秋木樹葉",
  "block.traverse.yellow_autumnal_sapling": "黃色秋木樹葉",
  "entity.traverse.fir_boat": "樅木船",
  "item.traverse.fir_boat": "樅木船",
  "itemGroup.traverse": "Traverse Reforged"
}

**Comment by noobanidus** [comment]
Hi there! Could you clarify that this is still correct for the most recent update? There were a few minor changes.

**Comment by ghost** [comment]
I have edited.
