### ISSUE TITLE
(Question) Will updating the mod badly effect saves that used a previous version? 

### ISSUE THREAD

**Issue by AbsorbingSafe11** [MysticMods/Traverse#29]
I have a planned to be long time world with the mod loaded and everything is working great, but the new update adds a new biome and affects an older biome. I wanted to know if updating will be safe or should I not update.
 (sorry if wrong location for question, but comments were disabled on the mod page and I couldn't find anywhere better to ask)

**Comment by noobanidus** [comment]
I don't believe it would be safe to do so due to some issues with forge & vanilla and how "biome shuffling" is handled. I'd recommend making a back-up of your world first, then update. If you do notice issues, downgrade to the previous version and restore from your back-up.

**Comment by AbsorbingSafe11** [comment]
Thank you for answering and information. (I previously wasn't sure how badly it would effect a world)

**Comment by noobanidus** [comment]
The negative effect would be randomisation of all of your biomes.
