### ISSUE TITLE
Fir saplings replace blocks when grown, autumnal saplings ignore blocks when grown

### ISSUE THREAD

**Issue by MoriyaShiine** [MysticMods/Traverse#3]
fir before: ![2019-10-19_18 25 29](https://user-images.githubusercontent.com/45156123/67152535-f4103180-f29d-11e9-9b7c-6d075c17fd1c.png)
fir after: ![2019-10-19_18 25 32](https://user-images.githubusercontent.com/45156123/67152538-fecac680-f29d-11e9-897f-ae46daf2b67a.png)
autumnal before: ![2019-10-19_18 25 18](https://user-images.githubusercontent.com/45156123/67152540-0a1df200-f29e-11e9-9777-09fcf51f2040.png)
autumnal after: ![2019-10-19_18 25 21](https://user-images.githubusercontent.com/45156123/67152541-11dd9680-f29e-11e9-9a67-22bbaeff579a.png)

**Comment by EpicSquid** [comment]
I... Idk how I didn't see this. Oops.

**Comment by noobanidus** [comment]
This appears to have been resolved so that a) functions as b) does.
