### ISSUE TITLE
[1.16.4] Setting the spawn weight of a biome to 0.0 doesn't disable its generation

### ISSUE THREAD

**Issue by Thombias** [MysticMods/Traverse#30]
### General Information

Describe the bug:
**Literally what the title says**

To Reproduce:
**1. Change the weight of any biome to 0.0 in the mod's config file
2. Save config & start Minecraft
3. Generate a new world
4. Fly around and notice how the biome is still generating
5. Tip: It's best to try out with the Meadows biome because it generates more often than others**

Expected behavior:
**The biome with a weight of 0.0 shouldn't generate at all according to the config's description
(It says setting the weight to 0.0 disables generation, but it doesn't)**
***

### Environment Versions
**traverse-1.16.4-0.4.3.4.jar**

Mystic Mods Versions
**NONE**

Other Versions:
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues: **Voyage (Adds a few new overworld biomes), Omni (Adds a single biome), maybe it could also be BetterEnd (Forge)**
- Forge: **forge-35.1.10**
- Minecraft: **1.16.4**
- Modpack (if available): **Personal WIP Modpack (136 Mods, only 3 of which add new biomes, no mod that changes the way worlds or terrain generates)**

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

Crash Report (if available):
**No crash**

Latest Log (if necessary):
-

### Additional Information
Screenshots (if available):
-

Additional context (optional):
-

**Comment by noobanidus** [comment]
Thanks for this. I'm not sure why I'm not getting notifications for Traverse in my GitHub feed, it's starting to annoy me. 

In theory those config values control the weights of the individual biomes after they're registered with the BiomeManager by Forge. I'll need to check to see if there's some other step I need to do in order to disable them instead now, things may have changed since 1.15.

**Comment by noobanidus** [comment]
Ah, I've worked out the cause and it's specifically with Meadows and a few other biomes -- they're set up to automatically replace some biomes (as per the original Fabric version) regardless of whether or not the biome is disabled.

**Comment by FastBoye127** [comment]
I'm still having this issue, specifically with the Rolling Hills biome.

**Comment by noobanidus** [comment]
Ah, that may have been the other one I forgot to fix.

**Comment by noobanidus** [comment]
I believe all of these issue should have been resolved as of the most recent release.
