### ISSUE TITLE
minecraft:swamp does not generate when Traverse is installed

### ISSUE THREAD

**Issue by Vazkii** [MysticMods/Traverse#32]
The vanilla swamp biome can't be found when Traverse is installed. Removing traverse causes it to spawn again.

**To Reproduce:**
Run `/locatebiome minecraft:swamp`.
![2020-12-31_19 09 01](https://user-images.githubusercontent.com/1794735/103423323-e17dd180-4b9d-11eb-978c-d4a16cbdf045.png)

***

### Environment Versions
* traverse-1.16.4-0.4.3.4
* forge-35.1.13

**Mystic Mods Versions**
MysticalLib is not installed.

**Other Versions:**
- Other mods you think could cause issues: Non-zero chance this has something to do with Environmental and the changes it makes to the biome.

***

### Logging Information
**Latest Log (if necessary):** https://pastebin.com/CtDgKzZ0

**Comment by Vazkii** [comment]
Additional info: I can not reproduce this using traverse-1.16.4-0.4.2.3

**Comment by noobanidus** [comment]
Thanks, fixing a few other bugs today so I'll dig into this.

**Comment by noobanidus** [comment]
Okay, I can replicate this in dev for the latest version without any other mod installed. I'll look into it further.

EDIT: This is pure stupidity on my part. I forgot to compensate for the actual *chance* to replace so instead every biome was replaced.
