### ISSUE TITLE
Fir logs and leaves not fully templated as trees

### ISSUE THREAD

**Issue by Syndaryl** [MysticMods/Traverse#36]
### General Information

**Describe the bug:**
Fir wood is not smeltable into charcoal, and fir leaves drop themselves, rather than being destroyed and having a chance of dropping saplings and sticks.

**To Reproduce:**
1. Find a fir tree
2. Cut it down
3. Be hailed by fir leaf blocks
4. Take fir wood and try to put in furnace
5. put coal in fuel slot, nothing happens.

The fur wood is burnable, however.

**Expected behavior:**
I expect the leaves to not drop leaf blocks. I expect instead they should be broken, and mostly not drop anything, but have a chance of instead dropping a stick or a fir sapling. 
I also expect the logs should be smeltable into charcoal.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib:  Not applicable
- Traverse Reforged: 1.16.4-0.4.3.6

**Other Versions:**
- Forge: 35.1.28 (I've tried other Forge versions from 35.0.10 on up - not every one, I admit. I got bored. But a bunch of them.
- Minecraft: 1.16.4

**Comment by noobanidus** [comment]
Are you sure about the fir leaves? I'm positive I fixed that in the previous build, but you're right that the charcoal recipe is missing.

**Comment by noobanidus** [comment]
Disregard my previous comment. I did all of it and forgot to re-run the data generator. Urgh.

**Comment by noobanidus** [comment]
This should be fixed in the latest release, thanks for the heads-up!

**Comment by Syndaryl** [comment]
No problem, and thank you for such a quick turn-around! I've spawned in plains right next to a fir wood and I'm short on wood alternatives :)
