### ISSUE TITLE
Autumnal leaves don't drop saplings.

### ISSUE THREAD

**Issue by Mysteriaa** [MysticMods/Traverse#37]
### General Information

**Describe the bug:**
 Leaves in the trees belonging to the Autumnal Wooded Hills  biome will drop in block form even when decaying, instead of things leaves normally would drop, like saplings, sticks, or apples, making their saplings impossible to obtain. I have tested this with red, yellow, brown, and orange autumnal leaves.

**To Reproduce:**

1. Break autumnal tree.
2. Any decaying leaves will drop as blocks.

**Expected behavior:**
 I don't think I need to be any clearer on this; autumnal leaves should drop saplings, etc.

***

### Environment Versions

**Mystic Mods Versions**

- Mystical World (0.3.1.4)
- Traverse Reforged (0.4.3.7)
**Other Versions:**
- Conflicting mod (if regarding mod integration): N/A
- Other mods you think could cause issues: N/A
- Forge:
- Minecraft: 1.16.4
- Modpack (if available): Personal modpack

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
Argh! I thought I had fixed all of them!

**Comment by noobanidus** [comment]
So, apparently I forgot to generate it after I fixed the other ones, then generated it after I had already made the release. Urgh. New version going up.
