### ISSUE TITLE
Fir door drops two items

### ISSUE THREAD

**Issue by PepperCode1** [MysticMods/Traverse#39]
### General Information

**Describe the bug:**
Breaking a fir door drops two items.
This is caused by the generated loot table not checking for the "lower" property of the door blockstate. (See vanilla door loot tables)

**To Reproduce:**
1. Break a fir door using any tool (or hand) in survival mode.

**Expected behavior:**
The door should only drop one item.

***

### Environment Versions

**Mystic Mods Versions**
- Traverse: 1.16.4-0.4.3.8

**Other Versions:**
- Forge: 35.1.36
- Minecraft: 1.16.4

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
This bug does not cause a crash.

**Latest Log (if necessary):**
There is nothing in the log related to this bug.

***

### Additional Information

There is no additional information.

**Comment by noobanidus** [comment]
Oops! That's definitely my bad, thank you.
