### ISSUE TITLE
minecraft crashes when generating world with specific seed

### ISSUE THREAD

**Issue by dromedar17** [MysticMods/Traverse#41]
When trying to generate a world with the seed -2998794942446541336, Minecraft crashes.
The behaviour is reproducible and the same on both 1.16.4 and 1.16.5.
Creating a new world with a different seed seems to work.

Game version: 1.16.4-forge-35.1.4 and 1.16.5-forge-36.0.43
no other mods present.

Potentially relevant part of the crash log:
java.lang.IllegalStateException: Unknown biome id emitted by layers: 65
[crash-2021-02-27_00.24.40-server.txt](https://github.com/MysticMods/Traverse/files/6053195/crash-2021-02-27_00.24.40-server.txt)

**Comment by noobanidus** [comment]
I'm afraid I can't reproduce this in my development environment using that seed with 1.16.4-forge-35.1.7. My dev environment isn't set up for 1.16.5-36.0.43 either.
