### ISSUE TITLE
Chunk generation problems / Crash when using /findbiome 

### ISSUE THREAD

**Issue by LtSeegson** [MysticMods/Traverse#42]
### General Information
Hi, 
Here to report a bug. He doesn't seems to be game breaking and is probably already fixed or you are already informed, but it cost nothing to inform you. I know it's an "old" version but the bug may be also occuring with more recent versions.
I've made a modpack with traverse, i noticed weird chunk generation (sort of mosaic), I thought it was mod incompatibility but after many test, to my surprise, I do not seems to be the case, I've tested with a new instance with only traverse and forge installed and I think i know where the bug come from. 

**Describe the bug:**

When using the command /findbiome, the scan start, if the player start moving during the scan, weird mosaic shaped chunk will generate (like a chess board with white=biome 1 and black = biome 2). Sometimes this can crash the game with a game ticking world exception.

**To Reproduce:**

1. Create a single player world in creative with only traverse installed
2. Reduce the render distance to 8 to reduce de chunk generation distance (That way we can see the weird generation before a biome is found and tp occur)
3. Go up mid-air in creative
4. Use the /findbiome traverse:biome to start a scan a locate the said biome
5. After entering the command, start moving forward to generate biome (during the scan)

**Expected behavior:**
A indication that the player should not move during the scan, maybe block him from moving so that such chunk are not generated. At least an informative text saying that the scan can cause chunk generation problem when moving.
***

**Mystic Mods Versions**
Traverse Reforged : Traverse-1.12.2-1.6.0-69.jar 

**Other Versions:**
- Conflicting mod (if regarding mod integration): None
- Other mods you think could cause issues: None
- Forge: forge-14.23.5.2854
- Minecraft: 1.12.2

***

**Crash Report :**
https://gist.github.com/LtSeegson/a5c35e5f829724810d88b12c66e8ca3d

***

### Additional Information
**Screenshot :**
![2021-03-05_19 42 11](https://user-images.githubusercontent.com/65467508/110159392-edc71a80-7dea-11eb-998e-c6a9d81ec8ec.png)

PS: Pardon my English, I'm French, I hope it was understandable enough.

**Comment by noobanidus** [comment]
Sorry, I'm not the programmer of the original 1.12 version of Traverse and there's no way for me to provide support for it.

**Comment by LtSeegson** [comment]
Oh, no problem, I wasn't expecting any help, as I said it's not game breaking, I just wanted to inform you in case this bug is present on more recent versions. And thanks for the mod, it's really incredible, I love it. Have a nice day! :p
