### ISSUE TITLE
1.16.5 feature placement server crash

### ISSUE THREAD

**Issue by MrKashew** [MysticMods/Traverse#43]
[Log here](https://gist.github.com/MrKashew/664fbb169084fa2a22e811fbbc9e5d26)

**Comment by noobanidus** [comment]
This is really confusing to me. As far as I can guess, something is causing the weighted list look-up to happen twice, perhaps across threads, which results in a Concurrent Modification Error. Unless you can reproduce this error outside of the pack, there's literally nothing I can do to investigate it properly.

Speaking of, is this replicable or does it only sometimes happen?

**Comment by noobanidus** [comment]
So further to this, managed to talk to some people who have a little more experience. Apparently, if another dimension is attempting to use the same weighted block state (i.e., the same feature) (or possible jsut weighted block state?) at the same time, a CME can occur.

TelepathicGrunt has thankfully given me a patch I can add to avoid it.

**Comment by noobanidus** [comment]
Apologies, this slipped my mind. It'll be included in the next release.
