### ISSUE TITLE
mini jungle water colors are fucked with shaders

### ISSUE THREAD

**Issue by zachsai** [MysticMods/Traverse#44]
### General Information
![image](https://user-images.githubusercontent.com/63996164/113729807-598bf400-96c5-11eb-81cd-4fbb0db7ad14.png)
mini jungle water colors are fucked with shaders
**Describe the bug:**

**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft:
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
While unfortunate, we don't support shaders.

This is the first report of this issue that I've ever had. Have you considered contacting the author of the shader to communicate with them, as it appears to be something on their end?

**Comment by noobanidus** [comment]
I'm going to close this issue as "optifine is unsupported", sorry. 

If anyone else is experiencing this outside of Optifine, please open a new issue or comment on this one.
