### ISSUE TITLE
Coniferous Wooded Hills Only Displaying Index Title

### ISSUE THREAD

**Issue by Robongio** [MysticMods/Traverse#47]
![2021-05-09_00 43 56](https://user-images.githubusercontent.com/18617748/117555532-5b4c2d00-b060-11eb-8d28-004e24114510.png) It's literally "bug"ging me, that no one hasn't fixed it yet. And I would have wanted to send a pull request, but I am currently not so good on coding .java into a class file.

**Comment by noobanidus** [comment]
That's rather strange, I'm not sure why it would be doing that -- I'm not even sure where it's getting that translation key from. My expectation would be that it presents the translation key if the key doesn't exist, but maybe it just converts it to the registry key... I'll look into it.

**Comment by Robongio** [comment]
> That's rather strange, I'm not sure why it would be doing that -- I'm not even sure where it's getting that translation key from. My expectation would be that it presents the translation key if the key doesn't exist, but maybe it just converts it to the registry key... I'll look into it.

**Comment by Robongio** [comment]
Thanks!

**Comment by noobanidus** [comment]
TelepathicGrunt pointed out where this was, it should be in the next release.
