### ISSUE TITLE
[1.18.2] failed to load a valid ResoucePackInfo

### ISSUE THREAD

**Issue by cleakey** [MysticMods/Traverse#53]
### General Information

**Describe the bug:**
After installing this mod and the mods it requires in a 1.18.2 minecraft with the forge and then starting that minecraft, I get the message "traverse-5.1.4.jar failed to load a valid ResourcePackInfo"

**To Reproduce:**
1. Install forge, this mod and the required mods for this mod in Minecraft
2. Start Minecraft with those mods installed, and the bar in the MOJANG STUDIOS screen will accumulate
3. A warning message "Warning while loading mods 1 warning has occurred during loading / File Mod File: failed to load a valid ResourcePackInfo / File Mod Flile: C:\Users\....traverse-5.1.4.jar failed to load a valid ResourcePackInfo" appears

### Environment Versions
**Mystic Mods Versions**
[traverse-5.1.4](https://legacy.curseforge.com/minecraft/mc-mods/traverse-reforged/files/4563277)

**Other Versions:**
- [terraform-forge-3.1.4.jar](https://legacy.curseforge.com/minecraft/mc-mods/terraformed-api-reforged/files/4558335)
- [TerraBlender Forge 1.18.2-1.2.0.126](https://legacy.curseforge.com/minecraft/mc-mods/terrablender/files/3957976)
- Forge:1.18.2-forge-40.2.9
- Minecraft:1.18.2

**Comment by cal1407** [comment]
+1 Having the same issue as well

**Comment by noobanidus** [comment]
I'm not sure who is currently maintaining this version of Traverse, but they do not have access to this repository for bug reports. Please leave a comment on the CurseForge page or message the maintainer.
