### ISSUE TITLE
Incompatibility with Terrestria

### ISSUE THREAD

**Issue by cal1407** [MysticMods/Traverse#54]
### General Information

**Describe the bug:**
Pretty straightforward. The game crashed on startup when running both Traverse and Terrestria together. Tried removing all of my other mods except the two mods and their dependencies and the game still crashed. Running Traverse alone on the other hand results in the "failed to load a valid ResoucePackInfo" message appearing, which has been reported by [cleakey](https://github.com/cleakey) below.

**To Reproduce:**
Simply run Terrestria and Traverse together along with their dependencies. 

### Logging Information
https://pastebin.com/9zhjnkG8

**Latest Log (if necessary):**
https://pastebin.com/9acUxMFN

**Comment by noobanidus** [comment]
I'm not sure who is currently maintaining this version of Traverse, but they do not have access to this repository for bug reports. Please leave a comment on the CurseForge page or message the maintainer.
