### ISSUE TITLE
[Parity Fix with Traverse Fabric] No rivers should generate in Plains Plateau

### ISSUE THREAD

**Issue by valoeghese** [MysticMods/Traverse#7]
Plains Plateau does not generate rivers in Traverse for fabric:(https://github.com/TerraformersMC/Traverse/blob/1.14.4/src/main/java/com/terraformersmc/traverse/generation/TraverseGeneration.java#L67)

To fix this parity on the forge version, `PlainsPlateauBiome` should override `public Biome getRiver()` to return itself as the river biome (made possible since https://github.com/MinecraftForge/MinecraftForge/commit/56857cf5e79f414c6d41e46d0660cf4f887402b5)

**Comment by noobanidus** [comment]
I think this is fixed int he next 1.15 release.
