### ISSUE TITLE
Missing fir wood derivatives

### ISSUE THREAD

**Issue by IronPiston** [MysticMods/Traverse#8]
**Describe your suggestion:**
Fir wood feels like a 2nd class citizen, lacking blocks/items added either by vanilla or mods:
- Boat
- Sign
- Ladder
- Chest
- Bookshelf

**Describe alternatives you've considered:**
Some of these like the ladder, chest, and bookshelf could require Quark to be installed to be included.

**Comment by noobanidus** [comment]
That would require compatibility on Quark's end, not ours.

Unfortunately the art assets were are using at the minute are limited to those available in the original Fabric version. Any additional assets would need to be contributed or created especially for these.
